import json
import csv
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field

class DataPoint(BaseModel):
    input_data: Dict[str, Any] = Field(
        description="The input data provided to the model for evaluation"
    )
    output_data: Dict[str, Any] = Field(
        description="The output generated by the model being evaluated"
    )
    annotation: Literal[0, 1] = Field(
        description="Binary annotation where 1 indicates correct output and 0 indicates incorrect output"
    )
    note: Optional[str] = Field(
        default=None,
        description="Optional note providing additional context about the annotation"
    )
    human_description: Optional[str] = Field(
        default=None,
        description="Optional human-provided description of the task or evaluation criteria"
    )
    additional_context: Optional[str] = Field(
        default=None,
        description="Optional field for any additional context or metadata"
    )

    def format(self, index: Optional[int] = None) -> str:
        """Format a single datapoint as a string"""
        parts = []
        if index is not None:
            parts.append(f"Example {index}:")
            
        parts.extend([
            "Input:",
            json.dumps(self.input_data, indent=2),
            "",
            "Output:",
            json.dumps(self.output_data, indent=2),
            "",
            f"Annotation: {'Correct' if self.annotation == 1 else 'Incorrect'}",
            f"Note: {self.note or 'N/A'}",
            "\n" + "-" * 50 + "\n"
        ])
        return "\n".join(parts)

    def to_dict(self, task_description: Optional[str] = None) -> Dict[str, Any]:
        """Convert datapoint to a standardized dictionary format"""
        result = {
            "input_data": self.input_data,
            "model_output": {"output": self.output_data},
            "annotation": self.annotation,
            "note": self.note
        }
        if task_description:
            result["task_description"] = task_description
        return result

    @classmethod
    def format_batch(cls, 
                    datapoints: List['DataPoint'], 
                    finalized_task_description: str) -> str:
        """Format a batch of datapoints with optional task description"""
        parts = []
        if finalized_task_description:
            parts.append(f"Task Description: {finalized_task_description}\n")
        
        parts.extend(dp.format(i + 1) for i, dp in enumerate(datapoints))
        return "\n".join(parts)

    @classmethod
    def from_example(cls, example: Dict[str, Any]) -> 'DataPoint':
        """
        Create a DataPoint object from a raw example dictionary.
        Adjust this method to handle different data formats.
        """
        input_data = example.get('input') or example.get('input_data') or example.get('question') or {}
        output_data = example.get('output') or example.get('output_data') or example.get('answer') or {}
        annotation = int(example.get('annotation', 0))
        note = example.get('note', '')

        # If input_data and output_data are strings, wrap them in dictionaries
        if isinstance(input_data, str):
            input_data = {'text': input_data}
        if isinstance(output_data, str):
            output_data = {'text': output_data}

        return cls(
            input_data=input_data,
            output_data=output_data,
            annotation=annotation,
            note=note,
        )

    model_config = {
        "json_schema_extra": {
            "example": {
                "input_data": {"text": "Example input"},
                "output_data": {"response": "Example output"},
                "annotation": 1,
                "note": "This is a good response",
                "human_description": "Task involves evaluating text responses",
                "additional_context": "From validation set"
            }
        }
    }

def load_data(file_path: str) -> List[DataPoint]:
    """
    Load data from a JSON or CSV file and convert it into a list of DataPoint objects.
    """
    data_points = []
    if file_path.endswith('.json'):
        with open(file_path, 'r') as f:
            data_list = json.load(f)
            for example in data_list:
                data_point = DataPoint.from_example(example)
                data_points.append(data_point)
    elif file_path.endswith('.csv'):
        with open(file_path, newline='', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                data_point = DataPoint.from_example(row)
                data_points.append(data_point)
    else:
        raise ValueError(f"Unsupported file format: {file_path}")
    return data_points