import json
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field

class DataPoint(BaseModel):
    input_data: Dict[str, Any] = Field(
        description="The input data provided to the model for evaluation"
    )
    output_data: Dict[str, Any] = Field(
        description="The output generated by the model being evaluated"
    )
    annotation: Literal[0, 1] = Field(
        description="Binary annotation where 1 indicates correct output and 0 indicates incorrect output"
    )
    note: Optional[str] = Field(
        default=None,
        description="Optional note providing additional context about the annotation"
    )
    human_description: Optional[str] = Field(
        default=None,
        description="Optional human-provided description of the task or evaluation criteria"
    )
    additional_context: Optional[str] = Field(
        default=None,
        description="Optional field for any additional context or metadata"
    )

    def format(self, index: Optional[int] = None) -> str:
        """Format a single datapoint as a string"""
        parts = []
        if index is not None:
            parts.append(f"Example {index}:")
            
        parts.extend([
            "Input:",
            json.dumps(self.input_data, indent=2),
            "",
            "Output:",
            json.dumps(self.output_data, indent=2),
            "",
            f"Annotation: {'Correct' if self.annotation == 1 else 'Incorrect'}",
            f"Note: {self.note or 'N/A'}",
            "\n" + "-" * 50 + "\n"
        ])
        return "\n".join(parts)

    def to_dict(self, task_description: Optional[str] = None) -> Dict[str, Any]:
        """Convert datapoint to a standardized dictionary format"""
        result = {
            "input_data": self.input_data,
            "model_output": {"output": self.output_data},
            "annotation": self.annotation,
            "note": self.note
        }
        if task_description:
            result["task_description"] = task_description
        return result

    @classmethod
    def format_batch(cls, 
                    datapoints: List['DataPoint'], 
                    task_description: Optional[str] = None) -> str:
        """Format a batch of datapoints with optional task description"""
        parts = []
        if task_description:
            parts.append(f"Task Description: {task_description}\n")
        
        parts.extend(dp.format(i + 1) for i, dp in enumerate(datapoints))
        return "\n".join(parts)

    model_config = {
        "json_schema_extra": {
            "example": {
                "input_data": {"text": "Example input"},
                "output_data": {"response": "Example output"},
                "annotation": 1,
                "note": "This is a good response",
                "human_description": "Task involves evaluating text responses",
                "additional_context": "From validation set"
            }
        }
    }