import json
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field

class DataPoint(BaseModel):
    input_data: Dict[str, Any] = Field(
        description="The input data provided to the model for evaluation"
    )
    output_data: Dict[str, Any] = Field(
        description="The output generated by the model being evaluated"
    )
    annotation: Literal[0, 1] = Field(
        description="Binary annotation where 1 indicates correct output and 0 indicates incorrect output"
    )
    note: Optional[str] = Field(
        default=None,
        description="Optional note providing additional context about the annotation"
    )
    human_description: Optional[str] = Field(
        default=None,
        description="Optional human-provided description of the task or evaluation criteria"
    )
    additional_context: Optional[str] = Field(
        default=None,
        description="Optional field for any additional context or metadata"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "input_data": {"text": "Example input"},
                "output_data": {"response": "Example output"},
                "annotation": 1,
                "note": "This is a good response",
                "human_description": "Task involves evaluating text responses",
                "additional_context": "From validation set"
            }
        }
    }

def format_all_datapoints(
    data: List[DataPoint], finalized_task_description: str
) -> str:
    formatted = [f"Task Description: {finalized_task_description}\n"]

    for i, dp in enumerate(data, 1):
        formatted.extend(
            [
                f"Example {i}:",
                "Input:",
                json.dumps(dp.input_data, indent=2),
                "",
                "Output:",
                json.dumps(dp.output_data, indent=2),
                "",
                f"Annotation: {'Correct' if dp.annotation == 1 else 'Incorrect'}",
                f"Note: {dp.note}",
                "\n" + "-" * 50 + "\n",  # Separator between examples
            ]
        )

    return "\n".join(formatted)

def convert_datapoint_to_example(
    task_description: str, data: List[DataPoint]
) -> List[Dict[str, Any]]:
    examples = []
    for dp in data:
        examples.append(
            {
                "task_description": task_description,
                "input_data": dp.input_data,
                "model_output": {"output": dp.output_data},
                "annotation": dp.annotation,
                "note": dp.note,
            }
        )
    return examples 